### ISSUE TITLE
prometheus error ParseFloat:invalid syntax

### ISSUE THREAD

**Issue by dmver2** [dabealu/zookeeper-exporter#10]
Metric "mntr{zk_host="localhost:2181"} is" - seems not parseable by prometheus:

level=warn ts=2019-07-03T08:50:17.786Z caller=scrape.go:937 component="scrape manager" scrape_pool=zookeeper
 target=http://HOST:4000/metrics msg="append failed" err="strconv.ParseFloat: parsing \"
is\": invalid syntax"

**Comment by dabealu** [comment]
Hi @dmver2 , could you please provide more details:
- your ZK version
- ZK config and flags
- output of `nc ZK_HOST ZK_PORT <<<mntr`

**Comment by dmver2** [comment]
curl localhost:8080/commands/mntr                                      
{                                                                                                  
  "version" : "3.5.5-390fe37ea45dee01bf87dc1c042b5e3dcce88653, built on 05/03/2019 12:07 GMT",     
  "avg_latency" : 0,                                                                               
  "max_latency" : 0,                                                                               
  "min_latency" : 0,                                                                               
  "packets_received" : 47176,                                                                      
  "packets_sent" : 14603,                                                                          
  "num_alive_connections" : 0,                                                                     
  "outstanding_requests" : 0,                                                                      
  "server_state" : "follower",                                                                     
  "znode_count" : 10,                                                                              
  "watch_count" : 0,                                                                               
  "ephemerals_count" : 2,                                                                          
  "approximate_data_size" : 500,                                                                   
  "open_file_descriptor_count" : 57,                                                               
  "max_file_descriptor_count" : 1048576,                                                           
  "last_client_response_size" : -1,                                                                
  "max_client_response_size" : -1,                                                                 
  "min_client_response_size" : -1,                                                                 
  "command" : "monitor",                                                                           
  "error" : null
}

**Comment by dmver2** [comment]
```
$ curl telnet://172.16.248.95:2181
mntr
mntr is not executed because it is not in the whitelist.
```

**Comment by dmver2** [comment]
ZK tuning required: -Dzookeeper.4lw.commands.whitelist=*

**Comment by dabealu** [comment]
Thanks for pointing out @dmver2 
I've made a fix to throw warning in exporter log and report `zk_up 0` if `mntr` isn't whitelisted.
https://github.com/dabealu/zookeeper-exporter/pull/11

**Comment by austince** [comment]
Hey, I've run into this same problem but am not as experienced with Zookeeper / how to tune it. Could someone possibly expand on the solution? Thank you!

**Comment by dabealu** [comment]
Hi @austince,
you need to add `4lw.commands.whitelist=mntr` line in your ZK config.
If you're using official docker ZK image, default config location is `/conf/zoo.cfg`.

You can find example of development cluster docker-compose and ZK configs below:
https://github.com/dabealu/zookeeper-exporter/blob/master/docker-compose.yml
https://github.com/dabealu/zookeeper-exporter/blob/master/zoo-conf/zoo.cfg.1
