### ISSUE TITLE
HTTP 404 while trying to access the metrics

### ISSUE THREAD

**Issue by vijaychhipa** [dabealu/zookeeper-exporter#13]
I started a local standalone Zookeeper instance of port 2181. 
Then build this source and created the container.

When I run it like this:

```
docker run dabealu/zookeeper-exporter:latest -listen=127.0.0.1:8080
2019/08/15 04:20:41 zookeeper addresses [127.0.0.1:2181]
2019/08/15 04:20:41 starting serving metrics at 127.0.0.1:8080/metrics
```

When I try to access the metrics:
curl -s 127.0.0.1:8080/metrics
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /metrics. Reason:
<pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.17.v20190418</a><hr/>

</body>
</html>

**Comment by dabealu** [comment]
Hi @vijaychhipa,
looks like you're already running some Java application using Jetty app server  on 8080 port, which is pointed in the error page: `Powered by Jetty:// 9.4.17.v20190418`.
Please stop this app first and restart exporter, or chose another port to run exporter by using `--listen` flag, e.g. `--listen=0.0.0.0:8090`
