### ISSUE TITLE
Publish binary releases?

### ISSUE THREAD

**Issue by akamensky** [dabealu/zookeeper-exporter#17]
I am fine to build it on my machine for testing etc, but when I want to deploy it to large amount of servers -- that is far from ideal. I'd suggest publishing binary releases along with source releases (so those can be pulled using Ansible for example).

**Comment by dabealu** [comment]
Will try to add build pipeline soon.

**Comment by dabealu** [comment]
Hi, new releases will contain prebuilt binaries, e.g. `0.1.3`:
https://github.com/dabealu/zookeeper-exporter/releases/tag/v0.1.3
