### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by andrii29** [dabealu/zookeeper-exporter#18]
Hello,
do you have some grafana dashboard example for collected metrics?

Regards,
Andrii

**Comment by dabealu** [comment]
Hi, no at the moment.
Would be great if you can provide some, otherwise I'll try to add, but no ETA.

**Comment by andrii29** [comment]
Hello,
I created simple dashboard for your exporter
https://grafana.com/grafana/dashboards/11442

Regards,
Andrii

**Comment by dabealu** [comment]
Nice, thank you !
