### ISSUE TITLE
leaderServes=no option breaks output

### ISSUE THREAD

**Issue by davemcphee** [dabealu/zookeeper-exporter#2]
We're using `leaderServes=no` option, meaning the leader only returns the string `This ZooKeeper instance is not currently serving requests` as a response to any 4 letter words. 

As a result, the exporter metrics output looks like this - note the bare string:
```
...
zk_ephemerals_count{zk_host="x.x.x.x:2181"} 129
zk_max_latency{zk_host="x.x.x.x:2181"} 4007
zk_packets_received{zk_host="x.x.x.x:2181" 19406771080
zk_outstanding_requests{zk_host="x.x.x.x:2181"} 19
This{zk_host="ip.of.leader:2181"} ZooKeeper
zk_max_latency{zk_host="x.x.x.x:2181"} 5664
zk_num_alive_connections{zk_host="x.x.x.x:2181"} 469
...
```

Prometheus is not a fan of this, of course: `strconv.ParseFloat: parsing "ZooKeeper": invalid syntax`

**Comment by dabealu** [comment]
I made a small fix for this case (https://github.com/dabealu/zookeeper-exporter/pull/3/files) and if this message appears in response exporter returns just 2 metrics for this ZK instance:
```
zk_up{zk_host="zkinstance:2181"} 1
zk_server_leader{zk_host="zkinstance:2181"} 1
```

It looks like this message can also appear if instance is just simply defunctional so this can be a little confusing.
Maybe its better to return zk_up=0 and zk_server_leader=1 or some other values in this case ?
