### ISSUE TITLE
Wrong up metric

### ISSUE THREAD

**Issue by andrii29** [dabealu/zookeeper-exporter#20]
Hello,

**echo stats | nc 127.0.0.1 2181**
This ZooKeeper instance is not currently serving requests

**curl 127.0.0.1:8090/metrics**
zk_up{zk_host="127.0.0.1:2181"} 1
zk_server_leader{zk_host="127.0.0.1:2181"} 1

Please fix this

Regards,
Andrii

**Comment by dabealu** [comment]
Hi @andrii29,
I guess it's correct - if instance is available but not serving requests due to `leaderServes=no` in zk config it's considered as leader:
https://github.com/dabealu/zookeeper-exporter/blob/master/main.go#L58

**Comment by dabealu** [comment]
Closing for now, feel free to reopen if it's incorrect behaviour.
