### ISSUE TITLE
Issue zk_peer_state prometheus parsing

### ISSUE THREAD

**Issue by vDMG** [dabealu/zookeeper-exporter#22]
Hello, 

I've found a strange issue related to the _zk_peer_state_ metric using the exporter with 3.6.0 zookeeper version. Using 3.5.7 zookeeper resolve this issue because the metric does not exist.

Indeed when i'm using prometheus to parse values from the exporter I'm having the followng error : 
`strconv.ParseFloat: parsing "leading": invalid syntax`

**Result of mntr command**

`echo mntr | nc localhost 2181 | grep peer`
 `zk_peer_state	leading - broadcast`

The same happen when nodes are following 

`echo mntr | nc localhost 2181 | grep peer`
 `zk_peer_state	following - broadcast`

May be it's a known issue but impossible for me to found it.
Thank you :)

**Comment by dabealu** [comment]
Hi @vDMG, thanks for reporting the issue, fixed in https://github.com/dabealu/zookeeper-exporter/pull/23
