### ISSUE TITLE
Add support for TLS

### ISSUE THREAD

**Issue by danpawlik** [dabealu/zookeeper-exporter#25]
Hi,
Since version 3.5, zookeeper has an option to enable TLS which is not supported by current exporter.

**Comment by dabealu** [comment]
Added in https://github.com/dabealu/zookeeper-exporter/pull/36
Thanks to @yozel

**Comment by poloz-lab** [comment]
What if we want to use TLS without client authentication (i.e. `ssl.clientAuth=none` in ZooKeeper configuration) ?
