### ISSUE TITLE
Tag version for docker image

### ISSUE THREAD

**Issue by kostya2011** [dabealu/zookeeper-exporter#7]
Hi, 
On a docker hub only latest tag is available 
May you please tag it with some version, so I can avoid using "FROM dabealu/zookeeper-exporter:latest" and use "FROM dabealu/zookeeper-exporter:<version>" instead. 

Thank you in advance.

**Comment by dabealu** [comment]
Hi, 
`latest` tag is the same as no tag at all, so
```
FROM dabealu/zookeeper-exporter
```
will use `latest` tag implicitly.

I also added `v0.1.0` tag which points to the current latest commit in master.
