### ISSUE TITLE
Support for ruok in zk_up?

### ISSUE THREAD

**Issue by crazed** [dabealu/zookeeper-exporter#8]
I like this exporter, but was hoping to also get a metric that covers the response from `ruok`. This would either be a new metric `zk_urok` or just update the `zk_up` to take this into account. I can submit a PR but wanted to see if you had any thoughts on a direction here.

**Comment by dabealu** [comment]
Hi @crazed, I think that it's better to have `zk_urok` as a separate metric because `zk_up` only represents state of network connectivity to the zk instance.
So we can have a case while `zk_up=1` but `zk_urok=0`, i.e. service is starting.
PR are welcome !
